Repository makrushinoff/StrongBody, pull requests merged in 2021-06, with the labels that each got.

#66 [Controller] Refactor controllers
  src/main/java/ua/strongBody/controller/CartController.java
  src/main/java/ua/strongBody/controller/ProductController.java
  src/main/java/ua/strongBody/dao/impl/ProductDAOIml.java
  src/main/java/ua/strongBody/facade/CartFacade.java
  src/main/java/ua/strongBody/facade/CartFacadeImpl.java
  src/main/java/ua/strongBody/mapper/ProductRowMapper.java
  src/main/java/ua/strongBody/models/Product.java
  src/main/java/ua/strongBody/processors/post/BookingPostProcessor.java
  src/main/java/ua/strongBody/processors/post/ProductPostProcessor.java
  src/main/java/ua/strongBody/services/impl/BookingServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/assets/templates/product/productAdd.html
  src/main/resources/database/initDB.sql
  src/main/resources/database/insertData.sql
  src/test/java/ua/strongBody/dao/BookingDAOImplIntegrationTest.java
  src/test/java/ua/strongBody/dao/ProductDAOImplIntegrationTest.java
  src/test/java/ua/strongBody/facade/CartFacadeTest.java
  src/test/java/ua/strongBody/mapper/ProductRowMapperTest.java
  src/test/java/ua/strongBody/services/impl/BookingServiceImplTest.java
  src/test/resources/schema.sql
Labels: bug, enhancement, refactoring

#67 [CustomerDAOImpl] Refactor queries and add unit tests
  src/main/java/ua/strongBody/dao/impl/CustomerDAOImpl.java
  src/test/java/ua/strongBody/dao/CustomerDAOImplUnitTest.java
Labels: enhancement, refactoring

#68 [DAO] Write unit tests to DAO layer and refactor queries
  src/main/java/ua/strongBody/dao/impl/BookingDAOImpl.java
  src/main/java/ua/strongBody/dao/impl/CartDAOImpl.java
  src/main/java/ua/strongBody/dao/impl/ProductDAOImpl.java
  src/test/java/ua/strongBody/dao/BookingDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/CartDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/CustomerDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/ProductDAOImplUnitTest.java
Labels: enhancement, refactoring

#69 [Validation] Add product creation validation
  src/main/java/ua/strongBody/validation/ProductValidator.java
  src/test/java/ua/strongBody/validation/ProductValidatorTest.java
  src/test/java/ua/strongBody/validation/RegistrationFormValidatorTest.java
Labels: critical, enhancement

#74 [Cart] Implement e2e price/sum branch
  src/main/java/ua/strongBody/controller/CartController.java
  src/main/java/ua/strongBody/dao/impl/CartDAOImpl.java
  src/main/java/ua/strongBody/facade/CartFacade.java
  src/main/java/ua/strongBody/facade/CartFacadeImpl.java
  src/main/java/ua/strongBody/models/Booking.java
  src/main/java/ua/strongBody/models/Cart.java
  src/main/java/ua/strongBody/processors/post/BookingPostProcessor.java
  src/main/java/ua/strongBody/processors/post/CartPostProcessor.java
  src/main/java/ua/strongBody/services/impl/CartServiceImpl.java
  src/main/resources/assets/templates/cart/cartView.html
  src/main/resources/assets/templates/product/productList.html
  src/test/java/ua/strongBody/dao/CartDAOImplUnitTest.java
  src/test/java/ua/strongBody/facade/CartFacadeTest.java
  src/test/java/ua/strongBody/services/impl/CartServiceImplTest.java
Labels: enhancement

#78 [Orders] Add e2e order logic
  src/main/java/ua/strongBody/assembly/OrderAssembly.java
  src/main/java/ua/strongBody/constants/LoggingConstants.java
  src/main/java/ua/strongBody/controller/CartController.java
  src/main/java/ua/strongBody/controller/MainController.java
  src/main/java/ua/strongBody/dao/OrderDAO.java
  src/main/java/ua/strongBody/dao/impl/OrderDAOImpl.java
  src/main/java/ua/strongBody/facade/OrderFacade.java
  src/main/java/ua/strongBody/facade/OrderFacadeImpl.java
  src/main/java/ua/strongBody/mapper/CartRowMapper.java
  src/main/java/ua/strongBody/mapper/OrderRowMapper.java
  src/main/java/ua/strongBody/models/Order.java
  src/main/java/ua/strongBody/populator/CartToOrderPopulator.java
  src/main/java/ua/strongBody/services/OrderService.java
  src/main/java/ua/strongBody/services/impl/BookingServiceImpl.java
  src/main/java/ua/strongBody/services/impl/OrderServiceImpl.java
  src/main/resources/assets/templates/cart/cartView.html
  src/main/resources/assets/templates/other/profile.html
  src/main/resources/database/initDB.sql
  src/test/java/ua/strongBody/assembly/OrderAssemblyTest.java
  src/test/java/ua/strongBody/dao/OrderDAOImplUnitTest.java
  src/test/java/ua/strongBody/facade/OrderFacadeImplTest.java
  src/test/java/ua/strongBody/mapper/OrderRowMapperTest.java
  src/test/java/ua/strongBody/services/impl/OrderServiceImplTest.java
Labels: enhancement

#79 [Refactoring] Transfer all DAO tests in correct dir
  src/test/java/ua/strongBody/dao/impl/BookingDAOImplIntegrationTest.java
  src/test/java/ua/strongBody/dao/impl/BookingDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/impl/CartDAOImplIntegrationTest.java
  src/test/java/ua/strongBody/dao/impl/CartDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/impl/CustomerDAOImplIntegrationTest.java
  src/test/java/ua/strongBody/dao/impl/CustomerDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/impl/OrderDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/impl/ProductDAOImplIntegrationTest.java
  src/test/java/ua/strongBody/dao/impl/ProductDAOImplUnitTest.java
Labels: refactoring

#80 [Refactoring] Code format in project
  src/main/java/ua/strongBody/config/SecurityConfig.java
  src/main/java/ua/strongBody/config/WebConfig.java
  src/main/java/ua/strongBody/controller/CartController.java
  src/main/java/ua/strongBody/dao/BookingDAO.java
  src/main/java/ua/strongBody/dao/CartDAO.java
  src/main/java/ua/strongBody/dao/CustomerDAO.java
  src/main/java/ua/strongBody/dao/OrderDAO.java
  src/main/java/ua/strongBody/dao/ProductDAO.java
  src/main/java/ua/strongBody/exceptions/FieldNotFoundException.java
  src/main/java/ua/strongBody/exceptions/FieldValidationException.java
  src/main/java/ua/strongBody/exceptions/ValidationException.java
  src/main/java/ua/strongBody/facade/CartFacade.java
  src/main/java/ua/strongBody/facade/OrderFacade.java
  src/main/java/ua/strongBody/facade/impl/CartFacadeImpl.java
  src/main/java/ua/strongBody/facade/impl/OrderFacadeImpl.java
  src/main/java/ua/strongBody/mapper/CartRowMapper.java
  src/main/java/ua/strongBody/models/Customer.java
  src/main/java/ua/strongBody/models/Role.java
  src/main/java/ua/strongBody/models/State.java
  src/main/java/ua/strongBody/models/forms/LoginForm.java
  src/main/java/ua/strongBody/models/forms/RegistrationForm.java
  src/main/java/ua/strongBody/populator/CartToOrderPopulator.java
  src/main/java/ua/strongBody/populator/Populator.java
  src/main/java/ua/strongBody/processors/post/BookingPostProcessor.java
  src/main/java/ua/strongBody/processors/post/PostProcessor.java
  src/main/java/ua/strongBody/processors/post/ProductPostProcessor.java
  src/main/java/ua/strongBody/services/BookingService.java
  src/main/java/ua/strongBody/services/CartService.java
  src/main/java/ua/strongBody/services/CustomerService.java
  src/main/java/ua/strongBody/services/OrderService.java
  src/main/java/ua/strongBody/services/ProductService.java
  src/main/java/ua/strongBody/services/RegistrationService.java
  src/main/java/ua/strongBody/validation/ProductValidator.java
  src/main/java/ua/strongBody/validation/Validator.java
  src/test/java/ua/strongBody/dao/impl/BookingDAOImplIntegrationTest.java
  src/test/java/ua/strongBody/dao/impl/BookingDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/impl/CartDAOImplIntegrationTest.java
  src/test/java/ua/strongBody/dao/impl/CartDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/impl/CustomerDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/impl/OrderDAOImplUnitTest.java
  src/test/java/ua/strongBody/dao/impl/ProductDAOImplUnitTest.java
  src/test/java/ua/strongBody/facade/CartFacadeTest.java
  src/test/java/ua/strongBody/facade/OrderFacadeImplTest.java
  src/test/java/ua/strongBody/services/impl/CartServiceImplTest.java
  src/test/java/ua/strongBody/services/impl/OrderServiceImplTest.java
  src/test/java/ua/strongBody/services/impl/ProductServiceImplTest.java
  src/test/java/ua/strongBody/validation/ProductValidatorTest.java
  src/test/java/ua/strongBody/validation/RegistrationFormValidatorTest.java
Labels: refactoring

#81 [Refactoring] Rewrite LoggingConstants to enum
  src/main/java/ua/strongBody/constants/LoggingConstants.java
  src/main/java/ua/strongBody/services/impl/BookingServiceImpl.java
  src/main/java/ua/strongBody/services/impl/CartServiceImpl.java
  src/main/java/ua/strongBody/services/impl/CustomerDetailsServiceImpl.java
  src/main/java/ua/strongBody/services/impl/CustomerServiceImpl.java
  src/main/java/ua/strongBody/services/impl/OrderServiceImpl.java
  src/main/java/ua/strongBody/services/impl/ProductServiceImpl.java
  src/main/java/ua/strongBody/services/impl/RegistrationServiceImpl.java
  src/main/java/ua/strongBody/validation/ProductValidator.java
  src/main/java/ua/strongBody/validation/RegistrationFormValidator.java
Labels: refactoring

#83 [Testing] Add parametrized tests to post processors
  src/main/java/ua/strongBody/processors/post/BookingPostProcessor.java
  src/main/java/ua/strongBody/processors/post/CartPostProcessor.java
  src/test/java/ua/strongBody/processors/post/BookingPostProcessorTest.java
  src/test/java/ua/strongBody/processors/post/CartPostProcessorTest.java
  src/test/java/ua/strongBody/processors/post/ProductPostProcessorTest.java
Labels: enhancement
