Repository makrushinoff/StrongBody, pull requests merged in 2021-05, with the labels that each got.

#14 [.gitignore] Update .gitignore and remove useless maven files
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  mvnw
  mvnw.cmd
Labels: refactoring

#15 [Docs] Create new docs folder
  docs/db_schema.jpg
Labels: documentation

#44 [Service] Add general service and Customer service impl
  src/main/java/ua/strongBody/services/CustomerService.java
  src/main/java/ua/strongBody/services/GeneralService.java
  src/main/java/ua/strongBody/services/impl/CustomerServiceImpl.java
Labels: critical, enhancement
